POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhcnphbiIsImlkIjoiNjc4NjA4YTVmMzBmY2E2NWYyZGExM2JjIiwiaWF0IjoxNzM2ODM4MDAwfQ.qCGuciboIg2kpcMzqQhHfiQKxmZTbqkDTF7QnjVh2Bc

{
    "title": "Viidakossa kuhisee",
    "author": "T. Arzani",
    "url": "http://hc-andersen.fi/",
    "likes": 0
}